# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-GF-sunk_Ba-3QeXhaelwXvXZOaK0jQ
"""

# Amazon sales analysis

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np
import pandas as pd # Ensures Pandas is imported and aliased as 'pd'
import matplotlib.pyplot as plt
import seaborn as sns

# import dataset
df = pd.read_csv('/content/amazon_sales.csv - Sheet1.csv') # Now 'pd' is recognized
df

# Basic operations
df.shape
df.head()

df.tail()

df.info()

# cheaking Null values
pd.isnull(df)

# total null values
pd.isnull(df).sum()

# remove null values
df.dropna()

df.isnull().sum()



# change data type
df['ship-postal-code'] = pd.to_numeric(df['ship-postal-code'], errors='coerce').astype('Int64')
df

#cheak data type
df['ship-postal-code'].dtype

df['Date'] = pd.to_datetime(df['Date'])
df

# describe the statistical method i.e 'mean','meadian' or 'mode' and many
df.describe()

# describe data with object datatype
df.describe(include='object')

#describe for specific column
df[['Qty','Amount']].describe()



#cheaking for Data labels
ax=sns.countplot(x='Size',data=df)
for bars in ax.containers:
  ax.bar_label(bars)



"""#most of the people buy m size

"""

# courier status
plt.figure(figsize=(10,6))
ax=sns.countplot(x='Courier Status',hue='Status',data=df)
plt.show(
)

"""# Majority of the order ship through the courier"""

df.head()

df['Category'] = df['Category'].astype('str')
c_d=df['Category']
plt.figure(figsize=(10,6))
plt.hist(c_d,bins=20,edgecolor='blue',color='g')
plt.xticks(rotation=90)
plt.show()



"""Most of the buyers are t-shirt"""

# cheak b2b data
B2b=df['B2B'].value_counts()
B2b

# create pie chart
plt.pie(B2b,labels=B2b.index,autopct='%1.2f%%')
plt.show()

"""max 99.32% buyers are retailers and 0.68% are wholesalers"""

# scatter plot
x_data=df['Category']
y_data=df['Size']
plt.scatter(x_data,y_data)
plt.xlabel('Category')
plt.ylabel('Size')
plt.title('Available size')
plt.show()

top10_states=df['ship-state'].value_counts().head(10)
top10_states
plt.figure(figsize=(12,6))
sns.countplot(data=df[df['ship-state'].isin(top10_states.index)],x='ship-state')
plt.xlabel('State')
plt.ylabel('Order_Count')
plt.title('Distribution of states')
plt.show()

"""# Most of the buyers are maharastra state"""













