# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBdO7PGm5mQFZS2I_4458XiYtF4j5n0S
"""

##PYTHON_diwali_sales_analysis PRTOJECTS (EXPLORATORY DATA ANALYSIS)

import numpy as np
import pandas as pd

df = pd.read_csv('/content/Diwali Sales Data.csv', encoding='unicode_escape')
df.shape
# to avoid encoding error, unicode_escape

df.info()

df.head()

df.tail()

# drop unrelated/Blank column
df.drop(['Status','unnamed1'], axis=1, inplace=True)
df

# cheak for null values
pd.isnull(df).sum()

# drop null values
df.dropna(inplace=True)
df

# initialize list of list
data_test=[['madhav', 11],['Gopi',15],['Keshav', ],['lalita', 16]]
data_test

# crete the pandas dataframe using list
df_test=pd.DataFrame(data_test,columns=['Name','Age'])
df_test

df_test.dropna()

df_test

# change Data type
df['Amount'] = df['Amount'].astype('int')
df['Amount'].dtypes

df.columns

#change column name
df.rename(columns={'Marital_Status':'Shaadi'})

# describe methods return description of the data in the dataframe(i.e count,mean ,median, mode)
df.describe()

# use describe for specific column
df[['Age','Orders','Amount']].describe()



"""# EXPLORATORY DATA ANALYSIS

Gender
"""

import matplotlib.pyplot as plt
import seaborn as sns
df.columns

ax=sns.countplot(x='Gender',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

sales_gen = df.groupby(['Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)
sales_gen

sns.barplot(x='Gender',y='Amount',data=sales_gen)



"""## Age"""

ax=sns.countplot(data=df,x='Age Group',hue='Gender')

for bars in ax.containers:
  ax.bar_label(bars)

ax=sns.countplot(data=df,x='Age Group',hue='Age Group')

for bars in ax.containers:
  ax.bar_label(bars)

# Total Amount vs Age Group
Sales_age=df.groupby(['Age Group'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.barplot(x='Age Group',y='Amount',data=Sales_age)



"""From above graph we can see that most of the buyers are age group bitween 26-35 yrs female"""



"""# State"""

# Total number of order from Top 10 states
sales_state = df.groupby(['State'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)
sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data=sales_state,x='State',y='Orders')

#Total Amount/sales from top 10 states
sales_state = df.groupby(['State'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)
sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data=sales_state,x='State',y='Amount')



"""# Marital Status


"""

ax=sns.countplot(data=df,x='Marital_Status')

sns.set(rc={'figure.figsize':(7,5)})
for bars in ax.containers:
  ax.bar_label(bars)

sales_states=df.groupby(['Marital_Status','Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)
sns.set(rc={'figure.figsize':(6,5)})
sns.barplot(data=sales_states,x='Marital_Status',y='Amount',hue='Gender')



"""# **Occupation**"""

sns.set(rc={'figure.figsize':(20,5)})
ax=sns.countplot(data=df,x='Occupation')

for bars in ax.containers:
  ax.bar_label(bars)

sales_states=df.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data=sales_states,x='Occupation',y='Amount')



"""from above graph we can the most buyer are working in IT,helthcare,aviation sector

"""



"""# Product Category"""

sns.set(rc={'figure.figsize':(20,5)})
ax=sns.countplot(data=df,x='Product_Category')

for bars in ax.containers:
  ax.bar_label(bars)

sales_states=df.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data=sales_states,x='Product_Category',y='Amount')

"""from above graph we can the most of the sold products are from food,footwear And Electronics Categories"""

sales_states=df.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data=sales_states,x='Product_ID',y='Orders')

fig1, ax1 = plt.subplots(figsize=(12,7))
df.groupby('Product_ID')['Orders'].sum().nlargest(10).sort_values(ascending=False).plot(kind='bar')



"""# Conclusion:"""

Married women age group 26-35 yrs from UP, Maharastra and Karnataka working in IT, Healthcare and Aviation are more likely to buy products from Food, Clothing and Electronics category



"""                                             # **Thank you**




"""



